version: '3'
services:
  web:
    image: mylog
    container_name: mylog
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    command: npm run dev